version: '3'
services:
  db:
    build:
      context: ./mysql/docker
      dockerfile: mysql.dockerFile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./api/docker
      dockerfile: golang.dockerFile
    volumes:
      - "./api:/go"
    container_name: golang_app
    ports:
      - "9097:8080"
    tty: true
    depends_on:
      - db
